### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by hum4n0A** [florylsk/ExecIT#1]
Hello! Thanks for the code, I have a question: What I need to install to run the dll in a target system that not have a VS 2022. I got this message when I run in a fresh system:
![Screenshot_311](https://github.com/florylsk/ExecIT/assets/16938080/18504047-18e6-4d5a-bf8e-5324d321d040)

I already install VC++ as well. Thanks

**Comment by florylsk** [comment]
Hello! 

Make sure you are compiling it with Multi-Threading instead of Multi-Threading DLL to avoid dependency problems (it is included in the configuration if you have cloned the repo).

![image](https://github.com/florylsk/ExecIT/assets/46110263/0b1feaa8-9572-4aff-a48e-fb0c0520bcd5)

Other than that, I would make sure you are using the correct DLL and Shellcode file name (missing file extension?).

Finally, I would also try another simpler shellcode to discard potential errors comming from its own instructions which may need a dependency that the target does not have installed, though I believe that would result in a crash, not a controlled error by rundll32.

**Comment by hum4n0A** [comment]
Hello!! I just changed the runtime library like you said. It's worked. Thanks!!

**Comment by florylsk** [comment]
Great to hear!! :)
